---
- name: Backup personal files with restic
  ansible.builtin.shell:
    cmd: >
      restic
      -r sftp:homeserver:/home/neumann/backup/restic/
      --password-file ~/.config/restic/password
      --verbose
      backup {{ syncthing_share_path }}
  become: true
  become_user: "{{ username }}"
  when: is_desktop
  changed_when: true
