---
- name: Backup personal files with restic
  ansible.builtin.command:
    cmd: >
      restic
      -r sftp:homeserver:/home/neumann/backup/restic/
      --password-file ~/.config/restic/password
      backup {{ syncthing_share_path }}
  become: true
  become_user: "{{ username }}"
  when: is_desktop
  register: restic_result
  changed_when: restic_result.stdout is not search("Files:\\s+0 new,\\s+0 changed")
