---
- name: Clean go cache
  ansible.builtin.command:
    cmd: go clean -cache
  become: true
  become_user: "{{ ansible_facts['user_id'] }}"
  changed_when: true
#
- name: Clean broken symlinks in home
  ansible.builtin.command:
    cmd: find /home/{{ username }} -xtype l -delete
  become: true
  changed_when: false
