- name: Clean go cache
  ansible.builtin.shell:
    cmd: go clean -cache
  become: yes
  become_user: "{{ ansible_facts['user_id'] }}"
#
- name: Clean broken symlinks in home
  ansible.builtin.shell:
    cmd: find /home/{{ username }} -xtype l -delete
  become: yes
  changed_when: false
