---
- name: Install desktops packages
  ansible.builtin.import_tasks: pacman.yml
#
- name: Install AUR packages
  ansible.builtin.import_tasks: yay.yml
#
- name: Install flatpak packages
  ansible.builtin.import_tasks: flatpak.yml
#
- name: Install Yazi plugins
  ansible.builtin.import_tasks: yazi.yml
#
- name: Configure desktop system settings
  ansible.builtin.import_tasks: system.yml
#
- name: Enable desktop services
  ansible.builtin.import_tasks: services.yml
#
- name: Reboot the system
  ansible.builtin.reboot:
    reboot_timeout: 120
