- name: Install audio with pipewire
  community.general.pacman:
    name:
      - alsa-firmware
      - alsa-plugins
      - alsa-tools
      - pipewire-alsa
      - pipewire-audio
      - pipewire-jack
      - pipewire-pulse
      - pipewire-docs
      - sof-firmware
    state: present
#
- name: Install desktop environment
  community.general.pacman:
    name:
      - brightnessctl
      - cliphist
      - gnome
      - grim
      - hyprland
      - hyprpaper
      - hyprsunset
      - mako
      - slurp
      - wayland
      - wofi
      - waybar
    state: present
#
- name: Install pdf readers
  community.general.pacman:
    name:
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf
    state: present
#
- name: Install more CLI tools
  community.general.pacman:
    name:
      - dictd
      - flite
      - mplayer
      - mpv
      - surfraw
      - taskd
    state: present
#
- name: Install notebook stuff
  community.general.pacman:
    name:
      - tlp
    state: present
# should be in a different file
- name: Install python package using pipx
  ansible.builtin.shell:
    cmd: pipx install {{ item }}
  become: no
  become_user: "{{ ansible_user_id }}"
  loop:
    - git-sim
    - radon
    - visidata
    - yt-dlp
