- name: Enable desktop services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
    masked: no
  loop:
    - gdm.service
    - thermald.service
    - tlp.service
