---
- name: Install desktop AUR packages using yay
  ansible.builtin.command:
    cmd: yay -S --sudoloop --noconfirm {{ item }}
  become: true
  become_user: "{{ username }}"
  loop:
    - activitywatch-bin
    - claude-code
    - dict-wn
    - newsraft
    # - megasync-bin
    # - typespeed
  changed_when: true
