---
- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
  when: not ansible_check_mode

- name: restart vaultwarden
  ansible.builtin.systemd_service:
    name: vaultwarden.service
    state: restarted
  become: true
  when: not ansible_check_mode

- name: restart glance
  ansible.builtin.systemd_service:
    name: glance.service
    state: restarted
  become: true
  when: not ansible_check_mode

- name: restart readeck
  ansible.builtin.systemd_service:
    name: readeck.service
    state: restarted
  become: true
  when: not ansible_check_mode
