---
- name: Create restic backup directory
  ansible.builtin.file:
    path: /home/{{ username }}/backup/restic
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  become: true
