---
- name: Install server packages
  ansible.builtin.import_tasks: pacman.yml
#
- name: Install AUR packages
  ansible.builtin.import_tasks: yay.yml
#
- name: Configure Jellyfin
  ansible.builtin.import_tasks: jellyfin.yml
#
- name: Configure pi-hole
  ansible.builtin.import_tasks: pihole.yml
#
- name: Configure Syncthing shared directory
  ansible.builtin.import_tasks: syncthing.yml
#
- name: Configure backup storage
  ansible.builtin.import_tasks: backup.yml
#
- name: Deploy vaultwarden
  ansible.builtin.import_tasks: vaultwarden.yml
#
- name: Deploy glance dashboard
  ansible.builtin.import_tasks: glance.yml
#
- name: Deploy readeck bookmarks
  ansible.builtin.import_tasks: readeck.yml
#
- name: Configure server firewall
  ansible.builtin.import_tasks: network.yml
#
- name: Enable server services
  ansible.builtin.import_tasks: services.yml
#
- name: Reboot the system
  ansible.builtin.reboot:
    reboot_timeout: 120
  when: reboot | default(false) | bool
