- name: Schedule weekly gravity update
  ansible.builtin.cron:
    name: pihole gravity update
    weekday: "0"
    hour: "3"
    minute: "0"
    user: root
    job: pihole -g
  become: yes
#
- name: Create pi-hole log directory
  ansible.builtin.file:
    path: /var/log/pihole
    state: directory
    owner: pihole
    group: pihole
    mode: "0755"
  become: yes
#
- name: Create pi-hole log files
  ansible.builtin.file:
    path: "/var/log/pihole/{{ item }}"
    state: touch
    owner: pihole
    group: pihole
    mode: "0644"
  loop:
    - pihole.log
    - FTL.log
  become: yes
#
- name: Set pi-hole upstream DNS servers
  ansible.builtin.command: pihole-FTL --config dns.upstreams '["1.1.1.1", "8.8.8.8"]'
  become: yes
  changed_when: false
#
- name: Set pi-hole web interface port
  ansible.builtin.command: pihole-FTL --config webserver.port 8080
  become: yes
  changed_when: false
#
- name: Update gravity
  ansible.builtin.command: pihole -g
  become: yes
  changed_when: false
