---
- name: Install pi-hole via AUR
  ansible.builtin.command:
    cmd: yay -S --sudoloop --noconfirm --needed {{ item }}
  become: true
  become_user: "{{ username }}"
  loop:
    - pi-hole-server
    - pi-hole-ftl
  changed_when: true
