- name: Install Flatpak
  community.general.pacman:
    name:
      - flatpak
    state: present

- name: Ensure Flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add the Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub

- name: Install the desired Flatpak desktop apps
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - com.github.johnfactotum.Foliate
    - com.github.muriloventuroso.pdftricks
    - com.github.tenderowl.frog
    - com.spotify.Client
    - com.transmissionbt.Transmission
    - com.valvesoftware.Steam
    - io.dbeaver.DBeaverCommunity
    - md.obsidian.Obsidian
    - net.ankiweb.Anki
    - net.mkiol.SpeechNote
    - net.puddletag.puddletag
    - org.DolphinEmu.dolphin-emu
    - org.citra_emu.citra
    - org.gimp.GIMP
    - org.kiwix.desktop
    - org.libreoffice.LibreOffice
    - org.mozilla.Thunderbird
    - org.upscayl.Upscayl
    - org.videolan.VLC
    - org.zealdocs.Zeal
    - site.someones.Lonewolf
    - us.zoom.Zoom
  when: "'desktop' in group_names"

- name: Update all Flatpak applications
  ansible.builtin.command: flatpak update -y
  become: yes
