- name: Install Flatpak
  community.general.pacman:
    name:
      - flatpak
    state: present

- name: Ensure Flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add the Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub

- name: Install the desired Flatpak desktop apps
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    # essentials
    # - org.mozilla.firefox
    - com.github.johnfactotum.Foliate
    - com.transmissionbt.Transmission
    - org.videolan.VLC
    # # basic desktop apps
    # - com.spotify.Client
    # - md.obsidian.Obsidian
    # - net.ankiweb.Anki
    # - org.gimp.GIMP
    # - org.libreoffice.LibreOffice
    # - org.mozilla.Thunderbird
    # - us.zoom.Zoom
    # # dev
    # - io.dbeaver.DBeaverCommunity
    # - io.missioncenter.MissionCenter
    # - org.gnome.meld
    # - org.kiwix.desktop
    # - org.zealdocs.Zeal
    # # utils
    # - com.github.muriloventuroso.pdftricks
    # - com.github.tenderowl.frog
    # - net.mkiol.SpeechNote
    # - net.puddletag
    # - org.upscayl.Upscayl
    # - site.someones.Lonewolf
    # # games
    # - com.valvesoftware.Steam
    # - org.DolphinEmu.dolphin-emu
    # - org.citra_emu.citra
  when: "'desktop' in group_names"

- name: Update all Flatpak applications
  ansible.builtin.command: flatpak update -y
  become: yes
