- name: Install core packages
  import_tasks: pacman.yml
#
- import_tasks: yay.yml
#
- name: Set system setting
  import_tasks: system.yml
  when: first_install | bool
#
- import_tasks: dotfiles.yml
#
- name: Set network and firewall settings
  import_tasks: network.yml
  when: first_install | bool
#
- name: Enable several services
  import_tasks: services.yml
