# TODO:
# - config for the desktop: wayland, sound, bluetooth
# - organize global variables
# - battery config for the laptop
# - hyperland
# - backup with btrfs
# - docker setup
# - pihole
# - synchthing
# - mega cloud
# - other service: nextcloud, plex etc
# - update yay, delete caches etc

- import_tasks: pacman-update.yml

- name: Run pacman install only on first install
  import_tasks: pacman-core.yml
  when: first_install | bool

- name: Set some system setting - first install only
  import_tasks: system-settings.yml
  when: first_install | bool

- import_tasks: yay.yml

- import_tasks: dotfiles.yml

- name: Set network and firewall setting - first install only
  import_tasks: network.yml
  when: first_install | bool

- import_tasks: services.yml

- name: Reboot the system
  ansible.builtin.reboot:
    reboot_timeout: 10
  when: first_install | bool
