- name: Install core packages
  import_tasks: pacman.yml
#
- import_tasks: yay.yml
#
- name: Set system setting
  import_tasks: system.yml
#
- import_tasks: dotfiles.yml
#
- name: Set network and firewall settings
  import_tasks: network.yml
#
- name: Enable several services
  import_tasks: services.yml

#
# - name: Misc shell setups
#   import_tasks: misc.yml
