- name: Install desktop environment
  community.general.pacman:
    name:
      - wayland
      - gnome
      - hyprland
    state: present

- name: Install audio with pipewire
  community.general.pacman:
    name:
      - pipewire-audio
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - pipewire-docs
    state: present

- name: Install pdf reader
  community.general.pacman:
    name:
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf
    state: present

- name: Install more CLI tools
  community.general.pacman:
    name:
      - dictd
      # - dict-wn
      - flite
      # - imagemagick
      - mplayer
      - mpv
      - scrot
      - surfraw
      - taskd
    state: present

# MORE NOTEBOOK STUFF
- name: Install Notebook Stuff
  community.general.pacman:
    name:
      - tlp
    state: present

- name: Install python package using pipx
  ansible.builtin.shell:
    cmd: pipx install {{ item }}
  become: no
  become_user: "{{ ansible_user_id }}"
  loop:
    - git-sim
    - radon
    - visidata
    - yt-dlp

- name: Upgrade python packages using pipx
  ansible.builtin.shell:
    cmd: pipx upgrade-all
  become: no
  become_user: "{{ ansible_user_id }}"

- name: Clean pip cache
  ansible.builtin.shell:
    cmd: pip cache purge
  become: no
  become_user: "{{ ansible_user_id }}"
