- name: Install core software
  community.general.pacman:
    name:
      # kernel related
      - linux
      - linux-firmware
      - linux-headers
      - base
      - base-devel
      # core tools
      - git
      - zram-generator
      # firmware related
      - fwupd
      - fwupd-docs
      - intel-ucode
      - udisks2
    state: present

- name: Install system services
  community.general.pacman:
    name:
      - cronie
      - fail2ban
      - networkmanager
      - openssh
      - reflector
      - syncthing
      - thermald
      - ufw
    state: present

- name: Install GNU packages
  community.general.pacman:
    name:
      - coreutils
      - diffutils
      - findutils
      - gawk
      - gcc
      - gcc-libs
      - grep
      - make
      - man-db
      - man-pages
      - sed
      - tree
      - which
    state: present

- name: Install archival utils
  community.general.pacman:
    name:
      - atool
      - bzip2
      - gzip
      - p7zip
      - tar
      - unrar
      - unzip
      - xz
      - zip
    state: present

- name: Install network utils
  community.general.pacman:
    name:
      - curl
      - wget
      - net-tools
      - gping
    state: present

- name: Install python packages
  community.general.pacman:
    name:
      - pyenv
      - python
      - python-pipx
      - uv
    state: present

- name: Install TUIs
  community.general.pacman:
    name:
      - bottom
      - ghostty
      - kitty
      - lazygit
      - neovim
      - python-pynvim
      - yazi
    state: present

- name: Install CLI tools
  community.general.pacman:
    name:
      - bash
      - bat
      - ctags
      - difftastic
      - duf
      - dust
      - eza
      - fd
      - fzf
      - git-delta
      - github-cli
      - hyperfine
      - jq
      - procs
      - ripgrep
      - ripgrep-all
      - rsync
      - starship
      - stow
      - tealdeer
      - tokei
      - words
      - yank
      - zoxide
      - zsh
      - zsh-autosuggestions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
    state: present

- name: Install Fonts
  community.general.pacman:
    name:
      - ttf-fira-code
      - ttf-firacode-nerd
      - ttf-hack-nerd
      - ttf-iosevka-nerd
    state: present

- name: Install Server Packages
  community.general.pacman:
    name:
      - jellyfin-server
      - jellyfin-web
      - pi-hole-ftl
      - pi-hole-server
    state: present
  when: "'servers' in group_names"
