# TODO: MOVE TO WAYLAND
- name: Install XORG BSPWM desktop environment
  community.general.pacman:
    name:
      - bspwm
      - clipmenu
      - dmenu
      - feh
      - polybar
      - redshift
      - rofi
      - rofi-calc
      - sxhkd
      - unclutter
    state: present

# TODO: MOVE TO FLATPAK
- name: Install GUI apps
  community.general.pacman:
    name:
      - arandr # XORG
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf
    state: present

  # CHECK IF NEEDED
- name: Install more CLI tools
  community.general.pacman:
    name:
      - dictd
      - dict-wn
      - flite
      - imagemagick
      - mplayer
      - mpv
      - scrot
      - surfraw
      - taskd
    state: present

# MORE NOTEBOOK STUFF
- name: Install Notebook Stuff
  community.general.pacman:
    name:
      - tlp
    state: present

# CHECK IF MASON CAN DO THAT
# - name: Install programming languages, runtimes and LSPs
#   community.general.pacman:
#     name:
#       - clang
#       - codespell
#       - ghc
#       - go
#       - go-tools
#       - julia
#       - ruff
#       - ruff-lsp
#       - rust
#       - sqlfluff
#       - stylua
#       - vale
#     state: present

# try to move all python stuff to here
- name: Install python package using pipx
  ansible.builtin.shell:
    cmd: pipx install {{ item }}
  become: no
  become_user: "{{ ansible_user_id }}"
  loop:
    - git-sim
    - isort
    - mypy
    - radon
    - visidata
    - yt-dlp

- name: Upgrade python packages using pipx
  ansible.builtin.shell:
    cmd: pipx upgrade-all
  become: no
  become_user: "{{ ansible_user_id }}"

- name: Clean pip cache
  ansible.builtin.shell:
    cmd: pip cache purge
  become: no
  become_user: "{{ ansible_user_id }}"
