- name: Enable multiple services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    masked: no
  loop:
    - NetworkManager.service
    - fstrim.timer
    - keyd.service
    - reflector.timer
    - sshd.service
    - thermald.service

- name: Restart multiple services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: reloaded
  loop:
    - NetworkManager.service
    - fstrim.timer
    - keyd.service
    - reflector.timer
    - sshd.service
    - thermald.service
