- name: Enable multiple services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: restarted
    masked: no
  loop:
    - NetworkManager.service
    - docker.service
    - fail2ban.service
    - fstrim.timer
    - fwupd.service
    - keyd.service
    - reflector.timer
    - sshd.service
    - syncthing@{{ username }}.service
    - thermald.service
    - udisks2.service
    - ufw.service
