- name: Enable multiple services
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    enabled: true
    masked: no
  loop:
    - reflector
    - NetworkManager
    - sshd

- name: Restart multiple services
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    state: reloaded
  loop:
    - reflector
    - NetworkManager
    - sshd
