- name: Enable multiple services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: restarted
    masked: no
  loop:
    - NetworkManager.service
    - fail2ban.service
    - fstrim.timer
    - keyd.service
    - reflector.timer
    - sshd.service
    - syncthing@{{ username }}.service
    - thermald.service
    - ufw.service

# - name: Restart multiple services
#   ansible.builtin.systemd_service:
#     name: "{{ item }}"
#     state: restarted
#   loop:
#     - NetworkManager.service
#     - fail2ban.service
#     - fstrim.service
#     - keyd.service
#     - reflector.service
#     - sshd.service
#     - syncthing@{{ username }}.service
#     - thermald.service
#     - ufw.service
