- name: change shell to zsh
  become: yes
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
#
- name: Regenerate grub config
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
#
- name: Change pacman config
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - {regexp: "^#Color$", replace: "Color"}
    - {regexp: "^#VerbosePkgLists$", replace: "VerbosePkgLists"}
    - {regexp: "^#ParallelDownloads = 5$", replace: "ParallelDownloads = 20"}
#
- name: Change jorunald max log size
  ansible.builtin.replace:
    path: /etc/systemd/journald.conf
    regexp: "^#SystemMaxUse=$"
    replace: "SystemMaxUse=256M"
#
- name: Set vm.swappiness to 1
  ansible.builtin.copy:
    dest: /etc/sysctl.d/10-swappiness.conf
    content: |
      vm.swappiness = 180
      vm.watermark_boost_factor = 0
      vm.watermark_scale_factor = 125
      vm.page-cluster = 0
    owner: root
    group: root
    mode: "0644"
  become: yes
#
- name: Set zram config
  ansible.builtin.copy:
    dest: /etc/systemd/zram-generator.conf
    content: |
      [zram0]
      zram-size = ram
      compression-algorithm = zstd
    owner: root
    group: root
    mode: "0644"
  become: yes
#
- name: Generate zram
  ansible.builtin.command: systemctl daemon-reload
#
- name: Start zram
  ansible.builtin.command: systemctl start /dev/zram0
#
- name: Create keyd dir
  ansible.builtin.file:
    path: /etc/keyd
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: yes
#
- name: Set keyd config
  ansible.builtin.copy:
    dest: /etc/keyd/default.conf
    content: |
      [ids]

      *

      [main]

      capslock = overload(meta, esc)
      insert = S-insert

      [alt]
      h = left
      j = down
      k = up
      l = right
    owner: root
    group: root
    mode: "0644"
  become: yes
