- name: Check if yay is installed
  ansible.builtin.raw: command -v yay
  register: yay_installed
  ignore_errors: yes
  become: yes
  become_user: "{{ username }}"

- name: Clone yay repository
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/home/{{ username }}/yay"
  become: yes
  become_user: "{{ username }}"
  when: yay_installed is failed

- name: Build and install yay
  ansible.builtin.shell:
    cmd: makepkg -si --noconfirm
    chdir: "/home/{{ username }}/yay"
  become: yes
  become_user: "{{ username }}"
  when: yay_installed is failed

- name: Install AUR package using yay
  ansible.builtin.shell:
    cmd: yay -S --noconfirm --needed {{ item }}
  become: no
  become_user: "{{ ansible_user_id }}"
  loop:
    - choose-rust-git
    - erdtree-bin
    - hadolint-bin
    - keyd
    - nnn-nerd
    - viddy
  when: first_install | bool

- name: Install Desktop AUR package using yay
  ansible.builtin.shell:
    cmd: yay -S --noconfirm {{ item }}
  become: no
  become_user: "{{ ansible_user_id }}"
  loop:
    - activitywatch-bin
    - fast
    - newsraft
    - typespeed
    # - bsp-layout
    # - megasync-bin
    # - picom-jonaburg-git
    # - rofi-bluetooth-git
    # - rofi-power-menu-git
    # - rofi-wifi-menu-git
    # - ueberzugpp
  when: "'desktops' in group_names"
