- name: Check if yay is installed
  ansible.builtin.raw: command -v yay
  register: yay_installed
  ignore_errors: yes
  become: yes
  become_user: "{{ username }}"

- name: Clone yay repository
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/home/{{ username }}/yay"
  become: yes
  become_user: "{{ username }}"
  when: yay_installed is failed

- name: Build and install yay
  ansible.builtin.shell:
    cmd: makepkg -si --noconfirm
    chdir: "/home/{{ username }}/yay"
  become: yes
  become_user: "{{ username }}"
  when: yay_installed is failed

- name: Refresh AUR index
  ansible.builtin.shell:
    cmd: yay -Syy --noconfirm
  become: yes
  become_user: "{{ username }}"

- name: Install AUR package using yay
  ansible.builtin.shell:
    cmd: yay -S --sudoloop --noconfirm --needed {{ item }}
  become: yes
  become_user: "{{ username }}"
  loop:
    - choose-rust-git
    - erdtree-bin
    - fast
    - hadolint-bin
    - keyd
    - lazydocker-bin
    - nnn-nerd
    - ueberzugpp
    - viddy
  when: first_install | bool

- name: Install Desktop AUR package using yay
  ansible.builtin.shell:
    cmd: yay -S --sudoloop --noconfirm {{ item }}
  become: yes
  become_user: "{{ username }}"
  loop:
    - activitywatch-bin
    - newsraft
    - typespeed
  when: "'desktops' in group_names"
